### ISSUE TITLE
AttributeError: 'DebertaModel' object has no attribute '_pre_load_hook'

### ISSUE THREAD

**Issue by HaoBytes** [manavkapadnis/Enigma_ArgMining#2]
Hello! I am trying to reproduce this work. But when I run the last line in the 3. Making Predictions on the New Generated Key_points.ipynb, I encounter the following error.
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-73-81a559ea430b>](https://localhost:8080/#) in <module>()
----> 1 predict_model (test_dataset,df_test, save_model,model_name = 'debertalarge')

3 frames
[/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in __getattr__(self, name)
   1176                 return modules[name]
   1177         raise AttributeError("'{}' object has no attribute '{}'".format(
-> 1178             type(self).__name__, name))
   1179 
   1180     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

AttributeError: 'DebertaModel' object has no attribute '_pre_load_hook'

Can I ask whether who encounter the same error and how to solve it

**Comment by manavkapadnis** [comment]
Hi @HarrywillDr, 
Thank you for using our code for your work.
if you could share your Google colabortary notebook/ the exact code that you have used, then I could help you better.
Regards, 
Manav

**Comment by HaoBytes** [comment]
Hi Manav,
[3_Making_Predictions_on_the_New_Generated_Key_points.ipynb.zip](https://github.com/manavkapadnis/Enigma_ArgMining/files/8277021/3_Making_Predictions_on_the_New_Generated_Key_points.ipynb.zip)

Thank you so much! And we appreciate your work!

Basically, it stuck on the last step. And may I ask what is the last file used for? I'm not quite sure what the last file means because there aren't too many comments.

I also tried to use T5 for generation based on your work (as I see you have also set prefix), but it didn't work well. This is beyond your job, but may I ask if you have any idea about this? 

Agian , thank you so much!

Best wishes,
Harry

**Comment by manavkapadnis** [comment]
Hi @HarrywillDr apologies for the delayed response.

I tried to rerun my code and I also faced the same error. I checked by searching on forums, however there was no solution. 
When I was submitting at the time of conference, I didn't face this issue.

I would suggest you should try the following:
1. download the zip file  (https://github.com/manavkapadnis/Enigma_ArgMining/blob/main/combined%20dataset%20with%20features.zip)

2. Train the deberta large model trained on dataset+noun features using this code (https://github.com/manavkapadnis/Enigma_ArgMining/blob/main/Track%201%20-%20Key%20Point%20Matching/Transformer%20on%20Noun%20or%20Dependency%20parsing%20features.ipynb)

3. use that model to do the predictions in (https://github.com/manavkapadnis/Enigma_ArgMining/blob/main/Track%202%20-%20Key%20Point%20Generation/3.%20Making%20Predictions%20on%20the%20New%20Generated%20Key_points.ipynb)

If you still face any issues, let me know, I'll train it on my computer and send the model to you..

PS: Next time you can just drop me an email on iammanavk@gmail.com, since I check Github once or twice in a week, so I might be late to reply.

Regards,
Manav

**Comment by HaoBytes** [comment]
Hi Manav,

Thank you for you help!

Best wishes,
Harry
